In [1]:
!pip install tensorflow

In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

The core data structures of Keras are layers and models.

In [4]:
!pip install matplotlib

In [5]:
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
(X_train, y_train),(X_test,y_test) = keras.datasets.mnist.load_data()

In [7]:
len(X_train)

60000

In [8]:
len(X_test)

10000

In [9]:
X_train[0].shape

(28, 28)

In [10]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [11]:
plt.matshow(X_train[10])

In [12]:
y_train[10]

3

In [13]:
X_train.shape

(60000, 28, 28)

In [14]:
X_train=X_train/255  # scale between 0 to 1 
X_test=X_test/255

In [15]:
x_train_flattened = X_train.reshape(len(X_train),28*28)
x_test_flattened = X_test.reshape(len(X_test),28*28)

In [16]:
model=keras.Sequential([    
    keras.layers.Dense(10,input_shape=(784,),activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
model.fit(x_train_flattened, y_train, epochs=5)

C:\Users\mukth\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8237 - loss: 0.7083
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9155 - loss: 0.3071
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9210 - loss: 0.2831
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9255 - loss: 0.2677
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9259 - loss: 0.2632



 sequential is a type of model which means stack of layers in the network
 dense means all the neuron at one layer is connected every other nueron in other layer
 """keras.layers.Dense(10,input_shape=(784,),activation='sigmoid)"""
 here 10 is output neuron
 input_shape is number of input neurons

# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ]
)
# Call model on a test input
x = tf.ones((3, 3))
y = model(x)

both are the same, how the actual sequential model works (instead of using a sequential model we can use this)

# Create 3 layers
layer1 = layers.Dense(2, activation="relu", name="layer1")
layer2 = layers.Dense(3, activation="relu", name="layer2")
layer3 = layers.Dense(4, name="layer3")

# Call layers on a test input
x = tf.ones((3, 3))
y = layer3(layer2(layer1(x)))

In [19]:
model.evaluate(x_test_flattened, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9130 - loss: 0.3062


[0.26970452070236206, 0.9241999983787537]

In [20]:
y_predicted=model.predict(x_test_flattened)
y_predicted[0]  # predict the probability of occurance of number

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


array([2.5494546e-02, 2.9312699e-07, 6.4941436e-02, 9.5905805e-01,
       3.1927985e-03, 8.0192126e-02, 1.2374625e-06, 9.9971879e-01,
       7.7286333e-02, 6.0037655e-01], dtype=float32)

In [21]:
np.argmax(y_predicted[0]) #calculate the max probability index

7

In [22]:
plt.matshow(X_test[1])

In [23]:
np.argmax(y_predicted[1])

2

In [24]:
y_predicted_labels=[np.argmax(i) for i in y_predicted]

In [25]:
cm=tf.math.confusion_matrix(labels=y_test,predictions=y_predicted_labels)
cm

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 966,    0,    1,    2,    0,    4,    4,    2,    1,    0],
       [   0, 1110,    3,    2,    0,    1,    4,    2,   13,    0],
       [   8,    9,  917,   19,   10,    3,   13,   10,   39,    4],
       [   4,    0,   15,  928,    0,   20,    3,   11,   22,    7],
       [   2,    1,    3,    1,  929,    0,   10,    3,   11,   22],
       [  10,    2,    3,   37,   12,  766,   20,    8,   29,    5],
       [  14,    3,    5,    1,    7,    9,  916,    2,    1,    0],
       [   1,    5,   22,    9,    9,    0,    0,  947,    3,   32],
       [   7,    7,    7,   24,    9,   24,    9,   12,  869,    6],
       [  11,    7,    1,   13,   44,    6,    0,   26,    7,  894]])>

In [26]:
!pip install seaborn

In [27]:
import seaborn as sns
plt.figure(figsize=(10,7))
#cm=tf.math.confusion_matrix(labels=y_test,predictions=y_predicted_labels)
sns.heatmap(cm,annot=True,fmt = 'd')
plt.xlabel('predicted')
plt.ylabel('truth')

Text(95.72222222222221, 0.5, 'truth')

In [28]:
model=keras.Sequential([
    keras.layers.Dense(100,input_shape=(784,),activation='relu'),
    keras.layers.Dense(10,activation='sigmoid')
])
tb_callbacks = tf.keras.callbacks.TensorBoard(log_dir="logs/",histogram_freq=1)
model.compile(
    optimizer='SGD',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
model.fit(x_train_flattened, y_train, epochs=5,callbacks=[tb_callbacks])

C:\Users\mukth\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 14s 6ms/step - accuracy: 0.7265 - loss: 1.0426
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9015 - loss: 0.3579
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9128 - loss: 0.3050
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9253 - loss: 0.2687
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9331 - loss: 0.2391


In [29]:
model.evaluate(x_test_flattened, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.9274 - loss: 0.2519


[0.21759724617004395, 0.9373999834060669]

In [30]:
y_predicted=model.predict(x_test_flattened)
y_predicted_labels=[np.argmax(i) for i in y_predicted]
cm=tf.math.confusion_matrix(labels=y_test,predictions=y_predicted_labels)
plt.figure(figsize=(10,7))
sns.heatmap(cm,annot=True,fmt = 'd')
plt.xlabel('predicted')
plt.ylabel('truth')

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


Text(95.72222222222221, 0.5, 'truth')

In [62]:
%load_ext tensorboard
%tensorboard --logdir logs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


Reusing TensorBoard on port 6007 (pid 8300), started 1:09:43 ago. (Use '!kill 8300' to kill it.)